definitions:
  models.Category:
    properties:
      children:
        items:
          $ref: '#/definitions/models.Category'
        type: array
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      parent:
        $ref: '#/definitions/models.Category'
      parentID:
        type: integer
      updated_at:
        type: string
    type: object
  models.Order:
    properties:
      created_at:
        type: string
      id:
        type: integer
      orderItems:
        items:
          $ref: '#/definitions/models.OrderItem'
        type: array
      totalPrice:
        type: number
      updated_at:
        type: string
      user:
        $ref: '#/definitions/models.User'
      userID:
        type: integer
    type: object
  models.OrderItem:
    properties:
      created_at:
        type: string
      id:
        type: integer
      order:
        $ref: '#/definitions/models.Order'
      orderID:
        type: integer
      product:
        $ref: '#/definitions/models.Product'
      productID:
        type: integer
      quantity:
        type: integer
      updated_at:
        type: string
    type: object
  models.Product:
    properties:
      category:
        $ref: '#/definitions/models.Category'
      categoryID:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      orders:
        items:
          $ref: '#/definitions/models.Order'
        type: array
      phone:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/callback:
    get:
      consumes:
      - application/json
      description: Exchanges code for token and authenticates user
      parameters:
      - description: OAuth State
        in: query
        name: state
        required: true
        type: string
      - description: Authorization Code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - OAuth2Password: []
      summary: Handle authentication callback
      tags:
      - auth
  /auth/login:
    get:
      consumes:
      - application/json
      description: Generates an OAuth state and redirects user to authentication provider
      produces:
      - application/json
      responses:
        "307":
          description: Redirecting
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Redirect user to authentication provider
      tags:
      - auth
  /health:
    get:
      consumes:
      - application/json
      description: Get health status of app
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get health status of app
      tags:
      - health
  /users:
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      security:
      - OAuth2Password: []
      summary: Get all users
      tags:
      - users
swagger: "2.0"
